export const ASSETS = [
  {
    symbol: "BTC",
    name: "Bitcoin",
    type: "CRYPTO",
    categories: ["MAJOR", "LAYER1"],
    color: "#F7931A",
    pricePrecision: 2,
    quantityPrecision: 5,
    featured: true,
  },
  {
    symbol: "ETH",
    name: "Ethereum",
    type: "CRYPTO",
    categories: ["MAJOR", "LAYER1", "DEFI"],
    color: "#7B8CF0",
    pricePrecision: 2,
    quantityPrecision: 4,
    featured: true,
  },
  { symbol: "SOL", name: "Solana", type: "CRYPTO", categories: ["MAJOR", "LAYER1"], color: "#A56BFF", pricePrecision: 2, quantityPrecision: 3, featured: true },
  { symbol: "BNB", name: "BNB", type: "CRYPTO", categories: ["MAJOR", "LAYER1"], color: "#F3BA2F", pricePrecision: 2, quantityPrecision: 3, featured: true },
  { symbol: "XRP", name: "XRP", type: "CRYPTO", categories: ["MAJOR", "LAYER1"], color: "#9AAFC8", pricePrecision: 4, quantityPrecision: 1, featured: true },
  { symbol: "ADA", name: "Cardano", type: "CRYPTO", categories: ["MAJOR", "LAYER1"], color: "#3C7BF0", pricePrecision: 4, quantityPrecision: 1 },
  { symbol: "DOGE", name: "Dogecoin", type: "CRYPTO", categories: ["MEME", "MAJOR"], color: "#C9A93A", pricePrecision: 5, quantityPrecision: 0 },
  { symbol: "USDT", name: "Tether USD", type: "STABLECOIN", categories: ["STABLECOIN"], color: "#26A17B", pricePrecision: 4, quantityPrecision: 2 },
  { symbol: "USDC", name: "USD Coin", type: "STABLECOIN", categories: ["STABLECOIN"], color: "#2F7FD8", pricePrecision: 4, quantityPrecision: 2 },
  { symbol: "FDUSD", name: "First Digital USD", type: "STABLECOIN", categories: ["STABLECOIN"], color: "#2BC6A4", pricePrecision: 4, quantityPrecision: 2 },
  { symbol: "AVAX", name: "Avalanche", type: "CRYPTO", categories: ["LAYER1"], color: "#E84142", pricePrecision: 3, quantityPrecision: 2 },
  { symbol: "DOT", name: "Polkadot", type: "CRYPTO", categories: ["LAYER1"], color: "#E6007A", pricePrecision: 3, quantityPrecision: 2 },
  { symbol: "TRX", name: "TRON", type: "CRYPTO", categories: ["LAYER1"], color: "#EF3B4B", pricePrecision: 5, quantityPrecision: 0 },
  { symbol: "TON", name: "Toncoin", type: "CRYPTO", categories: ["LAYER1"], color: "#1E9BE0", pricePrecision: 3, quantityPrecision: 2 },
  { symbol: "LTC", name: "Litecoin", type: "CRYPTO", categories: ["LAYER1"], color: "#5A7DB8", pricePrecision: 2, quantityPrecision: 3 },
  { symbol: "NEAR", name: "NEAR Protocol", type: "CRYPTO", categories: ["LAYER1"], color: "#2BC29A", pricePrecision: 3, quantityPrecision: 1 },
  { symbol: "ATOM", name: "Cosmos", type: "CRYPTO", categories: ["LAYER1"], color: "#8E91B8", pricePrecision: 3, quantityPrecision: 2 },
  { symbol: "SUI", name: "Sui", type: "CRYPTO", categories: ["LAYER1"], color: "#4DA2FF", pricePrecision: 4, quantityPrecision: 1 },
  { symbol: "APT", name: "Aptos", type: "CRYPTO", categories: ["LAYER1"], color: "#3FD1B0", pricePrecision: 3, quantityPrecision: 2 },
  { symbol: "LINK", name: "Chainlink", type: "CRYPTO", categories: ["DEFI"], color: "#3C6BE0", pricePrecision: 3, quantityPrecision: 2 },
  { symbol: "UNI", name: "Uniswap", type: "CRYPTO", categories: ["DEFI"], color: "#FF3E9A", pricePrecision: 3, quantityPrecision: 2 },
  { symbol: "AAVE", name: "Aave", type: "CRYPTO", categories: ["DEFI"], color: "#B86BC8", pricePrecision: 2, quantityPrecision: 3 },
  { symbol: "LDO", name: "Lido DAO", type: "CRYPTO", categories: ["DEFI"], color: "#F69988", pricePrecision: 4, quantityPrecision: 1 },
  { symbol: "CRV", name: "Curve DAO", type: "CRYPTO", categories: ["DEFI"], color: "#5C83D6", pricePrecision: 4, quantityPrecision: 1 },
  { symbol: "INJ", name: "Injective", type: "CRYPTO", categories: ["DEFI", "LAYER1"], color: "#2D9CFF", pricePrecision: 3, quantityPrecision: 2 },
  { symbol: "POL", name: "Polygon", type: "CRYPTO", categories: ["LAYER2"], color: "#8B5CF6", pricePrecision: 4, quantityPrecision: 1 },
  { symbol: "ARB", name: "Arbitrum", type: "CRYPTO", categories: ["LAYER2"], color: "#34A8F0", pricePrecision: 4, quantityPrecision: 1 },
  { symbol: "OP", name: "Optimism", type: "CRYPTO", categories: ["LAYER2"], color: "#FF3B50", pricePrecision: 4, quantityPrecision: 1 },
  { symbol: "STRK", name: "Starknet", type: "CRYPTO", categories: ["LAYER2"], color: "#EC796B", pricePrecision: 4, quantityPrecision: 1 },
  { symbol: "SHIB", name: "Shiba Inu", type: "CRYPTO", categories: ["MEME"], color: "#FFA409", pricePrecision: 8, quantityPrecision: 0 },
  { symbol: "PEPE", name: "Pepe", type: "CRYPTO", categories: ["MEME"], color: "#5AA84A", pricePrecision: 8, quantityPrecision: 0 },
  { symbol: "WIF", name: "dogwifhat", type: "CRYPTO", categories: ["MEME"], color: "#C69C6D", pricePrecision: 4, quantityPrecision: 1 },
  { symbol: "BONK", name: "Bonk", type: "CRYPTO", categories: ["MEME"], color: "#F8A31B", pricePrecision: 8, quantityPrecision: 0 },
  { symbol: "FLOKI", name: "Floki", type: "CRYPTO", categories: ["MEME"], color: "#E0A526", pricePrecision: 8, quantityPrecision: 0 },
];

const EVM = "^0x[a-fA-F0-9]{40}$";
const TRON = "^T[1-9A-HJ-NP-Za-km-z]{33}$";
const SOLANA = "^[1-9A-HJ-NP-Za-km-z]{32,44}$";

export const NETWORKS = [
  { asset: "USDT", code: "TRC20", name: "TRON (TRC20)", minDeposit: "10", minWithdrawal: "20", withdrawalFee: "1", confirmations: 20, addressPattern: TRON },
  { asset: "USDT", code: "ERC20", name: "Ethereum (ERC20)", minDeposit: "10", minWithdrawal: "30", withdrawalFee: "4", confirmations: 12, addressPattern: EVM },
  {
    asset: "USDT",
    code: "BEP20",
    name: "BNB Smart Chain (BEP20)",
    minDeposit: "10",
    minWithdrawal: "20",
    withdrawalFee: "0.5",
    confirmations: 15,
    addressPattern: EVM,
  },
  { asset: "USDC", code: "ERC20", name: "Ethereum (ERC20)", minDeposit: "10", minWithdrawal: "30", withdrawalFee: "4", confirmations: 12, addressPattern: EVM },
  { asset: "USDC", code: "SOL", name: "Solana", minDeposit: "5", minWithdrawal: "10", withdrawalFee: "1", confirmations: 1, addressPattern: SOLANA },
  {
    asset: "BTC",
    code: "BTC",
    name: "Bitcoin",
    minDeposit: "0.0001",
    minWithdrawal: "0.001",
    withdrawalFee: "0.0002",
    confirmations: 2,
    addressPattern: "^(bc1[a-z0-9]{25,59}|[13][a-km-zA-HJ-NP-Z1-9]{25,34})$",
  },
  {
    asset: "ETH",
    code: "ERC20",
    name: "Ethereum (ERC20)",
    minDeposit: "0.005",
    minWithdrawal: "0.01",
    withdrawalFee: "0.0015",
    confirmations: 12,
    addressPattern: EVM,
  },
  {
    asset: "ETH",
    code: "ARB",
    name: "Arbitrum One",
    minDeposit: "0.002",
    minWithdrawal: "0.005",
    withdrawalFee: "0.0002",
    confirmations: 12,
    addressPattern: EVM,
  },
  {
    asset: "BNB",
    code: "BEP20",
    name: "BNB Smart Chain (BEP20)",
    minDeposit: "0.01",
    minWithdrawal: "0.02",
    withdrawalFee: "0.0005",
    confirmations: 15,
    addressPattern: EVM,
  },
  { asset: "SOL", code: "SOL", name: "Solana", minDeposit: "0.05", minWithdrawal: "0.1", withdrawalFee: "0.005", confirmations: 1, addressPattern: SOLANA },
  {
    asset: "XRP",
    code: "XRP",
    name: "XRP Ledger",
    minDeposit: "5",
    minWithdrawal: "20",
    withdrawalFee: "0.25",
    confirmations: 1,
    addressPattern: "^r[1-9A-HJ-NP-Za-km-z]{24,34}$",
    memoRequired: true,
  },
  {
    asset: "DOGE",
    code: "DOGE",
    name: "Dogecoin",
    minDeposit: "20",
    minWithdrawal: "50",
    withdrawalFee: "4",
    confirmations: 40,
    addressPattern: "^D[5-9A-HJ-NP-U][1-9A-HJ-NP-Za-km-z]{32}$",
  },
  {
    asset: "ADA",
    code: "ADA",
    name: "Cardano",
    minDeposit: "5",
    minWithdrawal: "10",
    withdrawalFee: "0.8",
    confirmations: 15,
    addressPattern: "^addr1[0-9a-z]{50,110}$",
  },
];
