import { z } from "zod";
import { route } from "@/lib/api/route";
import { AppError } from "@/lib/api/errors";
import { prisma } from "@/lib/db/prisma";
import { audit } from "@/lib/services/audit";

/**
 * Registers a deposit address supplied by the platform's custodian/treasury.
 * Addresses are validated against the network's address pattern and are
 * never generated by the application.
 */
const schema = z.object({
  asset: z.string().min(2).max(10),
  network: z.string().min(2).max(20),
  address: z.string().trim().min(10).max(128),
  memo: z.string().trim().max(64).optional(),
  label: z.string().trim().max(80).optional(),
  userEmail: z.string().email().optional(),
});

export const POST = route({ admin: "settings.manage", body: schema }, async ({ session, body, ip }) => {
  const network = await prisma.network.findFirst({ where: { code: body.network, asset: { symbol: body.asset.toUpperCase() } } });
  if (!network) throw new AppError("UNSUPPORTED_NETWORK");
  if (network.addressPattern && !new RegExp(network.addressPattern).test(body.address)) throw new AppError("INVALID_ADDRESS");
  let userId = null;
  if (body.userEmail) {
    const u = await prisma.user.findUnique({ where: { email: body.userEmail.toLowerCase() } });
    if (!u) throw new AppError("NOT_FOUND", "No user with that email.");
    userId = u.id;
  }
  const row = await prisma.walletAddress.create({
    data: { networkId: network.id, userId, address: body.address, memo: body.memo || null, label: body.label || null, provider: "manual" },
  });
  await audit({
    actorId: session.user.id,
    actorEmail: session.user.email,
    ip,
    action: "wallet_address.create",
    targetType: "WalletAddress",
    targetId: row.id,
    metadata: { asset: body.asset, network: body.network, address: body.address, userId },
  });
  return { id: row.id };
});
